apiVersion: apps/v1
kind: Deployment
metadata:
  name: settlemint-service-helm
  namespace: settlemint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: settlemint-service-helm
  template:
    metadata:
      labels:
        app: settlemint-service-helm
    spec:
      containers:
        - name: settlemint-service-helm
          image: registry.hub.docker.com/patilruchita/settlemint1:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: settlemint-cm
          resources:
            limits:
                cpu: '1'
                memory: 2Gi
            requests:
                cpu: 500m
                memory: 1Gi
          livenessProbe:
            httpGet:
              path: /settlemint-service/api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /settlemint-service/api/health
              port: 8099
            initialDelaySeconds: 30
            periodSeconds: 10
      imagePullSecrets:
        - name: registry.hub.docker.com/patilruchita/settlemint1:latest
